name: INSPECT
description: "NDT Inspection System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  intl: ^0.20.2
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  fl_chart: ^1.0.0
  shared_preferences: ^2.5.3
  syncfusion_flutter_calendar: ^30.1.40
  table_calendar: ^3.2.0
  flutter_svg: ^2.2.0
  file_picker: ^10.2.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  connectivity_plus: ^6.1.5
  pdfx: ^2.9.2
  internet_connection_checker_plus: ^2.7.2
  archive: ^4.0.7
  web_socket_channel: ^3.0.3
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - env.dev
    - .env.staging
    - .env.prod
    - assets/images/

# Flutter Launcher Icons - THIS MUST BE AT ROOT LEVEL (NO INDENTATION)
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/logo_small.jpg"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  image_path: "assets/images/logo_small.jpg"